### ISSUE TITLE
cache & wal disk usage

### ISSUE THREAD

**Issue by FlorentCoppint** [cloudflare/utahfs#16]
Hi,
I'm testing UtahFS on Ubuntu.
I uploaded a 1.2GB directory, and it seems UtahFS stores the data twice on local device.
I have a ".utahfs" directory in $HOME, and "cache" + "wal" files are 1.2GB both !

```
florent@FloTux:~$ ls -alh .utahfs/
total 2,4G
drwxr--r--  2 florent florent 4,0K juin  12 17:31 .
drwxr----- 52 florent florent  24K juin  15 11:19 ..
-rw-r--r--  1 florent florent 1,2G juin  12 17:31 cache
-rw-r--r--  1 florent florent  19M juin  12 17:31 metadata
-rwxr--r--  1 florent florent  139 juin  15 03:17 pin.json
-rw-r--r--  1 florent florent 1,2G juin  12 17:31 wal
```
It's a huge loss of storage space. The goal is to store data on a S3 provider, not to store data twice on local disk !
How to resolve this issue ?
Thank you.
Florent

**Comment by Bren2010** [comment]
The WAL stores data temporarily while it's being uploaded to the remote storage provider, and over time it will drain. However, you won't necessarily get that space back because sqlite3 won't re-compact the database automatically. The max size of the WAL is controlled by the `max-wal-size` config setting which defaults to 128*1024 blocks, meaning you'd expect it to not get larger than ~2.2GB.

If this is too large for you, you can set the `max-wal-size` setting to something smaller and vacuum the database (after first turning off UtahFS):

```
$ sqlite3
SQLite version 3.28.0 2019-04-15 14:49:49
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
sqlite> .open .utahfs/wal
sqlite> VACUUM;
sqlite> ^D
$
```

----

The purpose of the cache on the other hand, is indeed to store at least one copy of your data locally for faster access. The max size of the cache is controlled by the `disk-cache-size` config setting which defaults to 3200*1024 blocks, meaning you'd expect it to not get larger than 107.4GB.

If this is too large for you, you can set it to something smaller (or -1 to disable) and vacuum the cache in the same way as the WAL.

---

Thanks for bringing these issues up, I've been meaning to write an "Advanced Configuration" document that discusses these sorts of things.

**Comment by Bren2010** [comment]
Additionally, I reduced the client-side default max cache size to 320*1024 (so a max of ~11GB).
