### ISSUE TITLE
QUESTION: Can one federate the block storage across multiple block storage providers?

### ISSUE THREAD

**Issue by seigel** [cloudflare/utahfs#4]
Hi! Great write up, and I will be taking it for a spin.  I was wondering if this, or others you may have stumbled across, allow me to store these `blocks` of information across mutiple providers with some redundancy like HDFS or something.  I am thinking that if any one provider does NOT have all the blocks I can a) feel even more comfortable about the content not being retrieved, b) if redundancy is done right, a provider going away and me losing files won't be a thing, and c) increased storage capacity by taking advantage of free tier options :)

Thanks!

**Comment by Bren2010** [comment]
This definitely wouldn't be hard to implement, but I decided not to include app-level redundancy because storage providers are *already* storing your data in a redundant fashion, such that you can reasonably expect them to never lose it. So it would be more technical complexity and month-to-month cost for very little benefit. I believe TahoeLAFS supports redundancy/federation though.

Thank you!
